name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install libraries
        run: |
          pip install pyTelegramBotAPI
          pip install requests
          pip install faker
          pip install beautifulsoup4
          pip install PyJWT
          pip install user-agent
          pip install getuseragent
          pip install aiohttp
          pip install lxml
          pip install cloudscraper

      - name: Run bot
        run: |
          python Passed.py
