name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyTelegramBotAPI requests faker beautifulsoup4

      - name: Run bot
        run: python main.py
